module.exports = {
    "RECIPE_DE_DE" : {
        "aatrox": "Dieser Champion wird gekontert von Jax, Riven, Teemo, Fiora und Renekton.Wie kann ich dir sonst helfen?",
        "ahri": "Dieser Champion wird gekontert von Annie, Diana, Kassadin, Talon und Swain. Wie kann ich dir sonst helfen?",
        "akali": "Dieser Champion wird gekontert von Lee Sin, Garen, Annie, Diana und Renekton. Wie kann ich dir sonst helfen?",
        "alistar": "Dieser Champion wird gekontert von Janna, Vayne, Lulu, Soraka und Morgana. Wie kann ich dir sonst helfen?",
        "amumu": "Dieser Champion wird gekontert von Shyvana, Lee Sin, Shaco, Xin Zhao und Dr. Mundo. Wie kann ich dir sonst helfen?",
        "anivia": "Dieser Champion wird gekontert von Fizz, Orianna, Kassadin, Diana und LeBlanc. Wie kann ich dir sonst helfen?",
        "annie": "Dieser Champion wird gekontert von Brand, Orianna, Lux, Morgana und Varus. Wie kann ich dir sonst helfen?",
        "ashe": "Dieser Champion wird gekontert von Ezreal, Caitlyn, Graves, Sivir und Draven. Wie kann ich dir sonst helfen?",
        "aurelion Sol": "Dieser Champion wird gekontert von Ahri, Kassadin, Fizz, Ekko und Katarina. Wie kann ich dir sonst helfen?",
        "azir": "Dieser Champion wird gekontert von Ziggs, Ahri, Zed, Fizz und Syndra. Wie kann ich dir sonst helfen?",
        "bard": "Dieser Champion wird gekontert von Morgana, Blitzcrank, Sivir, Thresh und Teemo. Wie kann ich dir sonst helfen?",
        "blitzcrank": "Dieser Champion wird gekontert von Leona, Alistar, Morgana, Thresh und Ezreal. Wie kann ich dir sonst helfen?",
        "brand": "Dieser Champion wird gekontert von Kassadin, LeBlanc, Fizz, Lux und Zed. Wie kann ich dir sonst helfen?",
        "braum": "Dieser Champion wird gekontert von Morgana, Zyra, Leona, Alistar und Lulu. Wie kann ich dir sonst helfen?",
        "caitlyn": "Dieser Champion wird gekontert von Sivir, Jinx, Varus, Tristana und Lucian. Wie kann ich dir sonst helfen?",
        "cassiopia": "Dieser Champion wird gekontert von Galio, Lux, LeBlanc, Fizz und Talon. Wie kann ich dir sonst helfen?",
        "cho'Gath": "Dieser Champion wird gekontert von Warwick, Garen, Kog'Maw, Vayne und Renekton. Wie kann ich dir sonst helfen?",
        "draven": "Dieser Champion wird gekontert von Varus, Caitlyn, Thresh, Blitzcrank und Quinn. Wie kann ich dir sonst helfen?",
        "ekko": "Dieser Champion wird gekontert von LeBlanc, Diana, Tryndamere, Cho'Gath und Yasuo. Wie kann ich dir sonst helfen?",
        "elise": "Dieser Champion wird gekontert von Kassadin, Yorick, Mordekaiser, Gangplank und Malzahar. Wie kann ich dir sonst helfen?",
        "evelynn": "Dieser Champion wird gekontert von Ryze, Rek'Sai, Twisted Fate, Lee Sin und Kassadin. Wie kann ich dir sonst helfen?",
        "ezreal": "Dieser Champion wird gekontert von Draven, Graves, Caitlyn, Miss Fortune und Vayne. Wie kann ich dir sonst helfen?",
        "fiddlesticks": "Dieser Champion wird gekontert von Janna, Xin'Zhao, Tristana, Diana und Alistar. Wie kann ich dir sonst helfen?",
        "fiora": "Dieser Champion wird gekontert von Jax, Pantheon, Darius, Renekton und Singed. Wie kann ich dir sonst helfen?",
        "fizz": "Dieser Champion wird gekontert von Ryze, Diana, Mordekaiser, Akali und Annie. Wie kann ich dir sonst helfen?",
        "galio": "Dieser Champion wird gekontert von Udyr, Janna, Braum, Yasuo und Talon. Wie kann ich dir sonst helfen?",
        "gangplank": "Dieser Champion wird gekontert von Pantheon, Fiora, Irelia, Riven und Jax. Wie kann ich dir sonst helfen?",
        "garen": "Dieser Champion wird gekontert von Teemo, Pantheon, Darius, Jayce und Yorick. Wie kann ich dir sonst helfen?",
        "gnar": "Dieser Champion wird gekontert von Irelia, Riven, Pantheon, Teemo und Darius. Wie kann ich dir sonst helfen?",
        "gragas": "Dieser Champion wird gekontert von Fizz, Yasuo, Ahri, LeBlanc und Mordekaiser. Wie kann ich dir sonst helfen?",
        "graves": "Dieser Champion wird gekontert von Caitlyn, Sivir, Miss Fortune, Corki und Urgot. Wie kann ich dir sonst helfen?",
        "hecarim": "Dieser Champion wird gekontert von Nasus, Sejuani, Aatrox, Vi und Lee Sin. Wie kann ich dir sonst helfen?",
        "heimerdinger": "Dieser Champion wird gekontert von Syndra, Lux, Ziggs, Xerath und Vel'Koz. Wie kann ich dir sonst helfen?",
        "illaoi": "Dieser Champion wird gekontert von Lulu, Tryndamere, Nasus, Fiora und Irelia. Wie kann ich dir sonst helfen?",
        "irelia": "Dieser Champion wird gekontert von Olaf, Renekton, Darius, Jax und Nasus. Wie kann ich dir sonst helfen?",
        "ivern": "Dieser Champion wird gekontert von Jax, Maokai, Sona, Singed und Fizz. Wie kann ich dir sonst helfen?",
        "janna": "Dieser Champion wird gekontert von Sona, Nami, Blitzcrank, Sivir und Diana. Wie kann ich dir sonst helfen?",
        "jarvan": "Dieser Champion wird gekontert von Yorick, Shen, Vi, Jax und Renekton. Wie kann ich dir sonst helfen?",
        "jax": "Dieser Champion wird gekontert von Malphite, Renekton, Garen, Singed und Pantheon. Wie kann ich dir sonst helfen?",
        "jayce": "Dieser Champion wird gekontert von Yorick, Irelia, Fiora, Nidalee und Xin'Zhao. Wie kann ich dir sonst helfen?",
        "jhin": "Dieser Champion wird gekontert von Ashe, Jinx, Lucian, Caitlyn und Ezreal. Wie kann ich dir sonst helfen?",
        "jinx": "Dieser Champion wird gekontert von Ezreal, Corki, Sivir, Lucian und Draven. Wie kann ich dir sonst helfen?",
        "kalista": "Dieser Champion wird gekontert von Ashe, Caitlyn, Vayne, Graves und Quinn. Wie kann ich dir sonst helfen?",
        "karma": "Dieser Champion wird gekontert von Veigar, Nami, Malzahar, Talon und Xerath. Wie kann ich dir sonst helfen?",
        "karthus": "Dieser Champion wird gekontert von Kassadin, Fizz, Katarina, Soraka und LeBlanc. Wie kann ich dir sonst helfen?",
        "kassadin": "Dieser Champion wird gekontert von Talon, Zed, Fizz, Heimerdinger und Pantheon. Wie kann ich dir sonst helfen?",
        "katarina": "Dieser Champion wird gekontert von Diana, Malzahar, Fizz, Fiddlesticks und LeBlanc. Wie kann ich dir sonst helfen?",
        "kayle": "Dieser Champion wird gekontert von Diana, Malzahar, Fizz, Fiddlesticks und LeBlanc. Wie kann ich dir sonst helfen?",
        "kennen": "Dieser Champion wird gekontert von Ryze, Swain, Janna, Irelia und Diana. Wie kann ich dir sonst helfen?",
        "kha'Zix": "Dieser Champion wird gekontert von Lee Sin, Rengar, Jayce, Jax und Pantheon. Wie kann ich dir sonst helfen?",
        "kindred": "Dieser Champion wird gekontert von Lee Sin, Diana, Vayne, Gragas und Jax. Wie kann ich dir sonst helfen?",
        "kled": "Dieser Champion wird gekontert von Darius, Garen, Jax, Yasuo und Gnar. Wie kann ich dir sonst helfen?",
        "kog'Maw": "Dieser Champion wird gekontert von Blitzcrank, Lucian, Jinx, Miss Fortune und Ashe. Wie kann ich dir sonst helfen?",
        "leBlanc": "Dieser Champion wird gekontert von Galio, Diana, Fizz, Morgana und Syndra.  Wie kann ich dir sonst helfen?",
        "lee Sin": "Dieser Champion wird gekontert von Trundle, Renekton, Udyr, Garen und Riven. Wie kann ich dir sonst helfen?",
        "leona": "Dieser Champion wird gekontert von Morgana, Alistar, Janna, Lulu und Thresh. Wie kann ich dir sonst helfen?",
        "lissandra": "Dieser Champion wird gekontert von Kassadin, Diana, Brand, Anivia und LeBlanc. Wie kann ich dir sonst helfen?",
        "lucian": "Dieser Champion wird gekontert von Vayne, Ezreal, Draven, Tristana und Caitlyn. Wie kann ich dir sonst helfen?",
        "lulu": "Dieser Champion wird gekontert von Soraka, Sona, Syndra, Brand und Orianna. Wie kann ich dir sonst helfen?",
        "lux": "Dieser Champion wird gekontert von Talon, Fizz, Katarina, Zed und Gragas. Wie kann ich dir sonst helfen?",
        "malphite": "Dieser Champion wird gekontert von Rumble, Cho'Gath, Olaf, Zac und Vladimir. Wie kann ich dir sonst helfen?",
        "malzahar": "Dieser Champion wird gekontert von Gangplank, Lux, Syndra, Talon und Morgana. Wie kann ich dir sonst helfen?",
        "maokai": "Dieser Champion wird gekontert von Shyvana, Nasus, Mundo, Pantheon und Swain. Wie kann ich dir sonst helfen?",
        "master Yi": "Dieser Champion wird gekontert von Jax, Teemo, Rammus, Tryndamere und Cho'Gath. Wie kann ich dir sonst helfen?",
        "miss Fortune": "Dieser Champion wird gekontert von Tristana, Draven, Caitlyn, Varus und Taric. Wie kann ich dir sonst helfen?",
        "mordekaiser": "Dieser Champion wird gekontert von Garen, Zyra, Swain, Lux und Yorick. Wie kann ich dir sonst helfen?",
        "morgana": "Dieser Champion wird gekontert von Talon, Karma, Katarina, Vladimir und Mordekaiser. Wie kann ich dir sonst helfen?",
        "mundo": "Dieser Champion wird gekontert von Riven, Kog'Maw, Olaf, Darius und Fizz. Wie kann ich dir sonst helfen?",
        "nami": "Dieser Champion wird gekontert von Lulu, Ezreal, Leona, Blitzcrank und Sona. Wie kann ich dir sonst helfen?",
        "nasus": "Dieser Champion wird gekontert von Teemo, Riven, Darius, Garen und Pantheon. Wie kann ich dir sonst helfen?",
        "nautilus": "Dieser Champion wird gekontert von Shyvana, Morgana, Yorick, Olaf und Vi. Wie kann ich dir sonst helfen?",
        "nidalee": "Dieser Champion wird gekontert von Yasuo, Pantheon, Akali, Fizz und Zed. Wie kann ich dir sonst helfen?",
        "nocturne": "Dieser Champion wird gekontert von Olaf, Udyr, Lee Sin, Vi und Shyvana. Wie kann ich dir sonst helfen?",
        "nunu": "Dieser Champion wird gekontert von Cassiopia, Sona, Soraka, Sivir und Riven. Wie kann ich dir sonst helfen?",
        "olaf": "Dieser Champion wird gekontert von Kennen, Kayle, Volibear, Yorick und Pantheon. Wie kann ich dir sonst helfen?",
        "orianna": "Dieser Champion wird gekontert von LeBlanc, Syndra, Ahri, Diana und Zed. Wie kann ich dir sonst helfen?",
        "pantheon": "Dieser Champion wird gekontert von Shen, Darius, Olaf, Malphite und Elise. Wie kann ich dir sonst helfen?",
        "poppy": "Dieser Champion wird gekontert von Olaf, Darius, Teemo, Kennen und Renekton. Wie kann ich dir sonst helfen?",
        "quinn": "Dieser Champion wird gekontert von Caitlyn, Varus, Miss Fortune, Caitlyn und Graves. Wie kann ich dir sonst helfen?",
        "rammus": "Dieser Champion wird gekontert von Tundle, Vi, Shyvana, Rek'Sai und Soraka. Wie kann ich dir sonst helfen?",
        "rek'Sai": "Dieser Champion wird gekontert von Fizz, Darius, Irelia, Gangplank und Kennen. Wie kann ich dir sonst helfen?",
        "renekton": "Dieser Champion wird gekontert von Garen, Pantheon, Ryze, Trundle und Vayne. Wie kann ich dir sonst helfen?",
        "rengar": "Dieser Champion wird gekontert von Jax, Fiora, Lee Sin, Pantheon und Riven. Wie kann ich dir sonst helfen?",
        "riven": "Dieser Champion wird gekontert von Garen, Olaf, Renekton, Darius und Jax. Wie kann ich dir sonst helfen?",
        "rumble": "Dieser Champion wird gekontert von Yorick, Xin'Zhao, Riven, Darius und Jayce. Wie kann ich dir sonst helfen?",
        "ryze": "Dieser Champion wird gekontert von Cassiopia, Lux, Orianna, Brand und Xerath. Wie kann ich dir sonst helfen?",
        "sejuani": "Dieser Champion wird gekontert von Xin Zhao, Vi, Evelynn, Lee Sin und Elise. Wie kann ich dir sonst helfen?",
        "shaco": "Dieser Champion wird gekontert von Lee Sin, Udyr, Vi, Warwick und Shyvana. Wie kann ich dir sonst helfen?",
        "shen": "Dieser Champion wird gekontert von Yorick, Vladimir, Jayce, Warwick und Teemo. Wie kann ich dir sonst helfen?",
        "shyvana": "Dieser Champion wird gekontert von Olaf, Trundle, Pantheon, Darius und Teemo. Wie kann ich dir sonst helfen?",
        "singed": "Dieser Champion wird gekontert von Teemo, Jayce, Vladimir, Kayle und Elise. Wie kann ich dir sonst helfen?",
        "sion": "Dieser Champion wird gekontert von Garen, Nasus, Riven, Jax und Pantheon. Wie kann ich dir sonst helfen?",
        "sivir": "Dieser Champion wird gekontert von Vayne, Draven, Twitch, Tristana und Kog'Maw. Wie kann ich dir sonst helfen?",
        "skarner": "Dieser Champion wird gekontert von Morgana, Xin'Zhao, Trundle, Gangplank und Olaf. Wie kann ich dir sonst helfen?",
        "sona": "Dieser Champion wird gekontert von Blitzcrank, Leona, Thresh, Miss Fortune und Draven. Wie kann ich dir sonst helfen?",
        "soraka": "Dieser Champion wird gekontert von Gnar, Miss Fortune, Blitzcrank, Tristana und Zac. Wie kann ich dir sonst helfen?",
        "swain": "Dieser Champion wird gekontert von Viktor, Lux, Cassiopia, Fizz und LeBlanc. Wie kann ich dir sonst helfen?",
        "syndra": "Dieser Champion wird gekontert von Fizz, Lux, Talon, Kassadin und Akali. Wie kann ich dir sonst helfen?",
        "tahm Kench": "Dieser Champion wird gekontert von Janna, Vayne, Gnar, Jax und Singed. Wie kann ich dir sonst helfen?",
        "taliyah": "Dieser Champion wird gekontert von Annie, Katarina, Ekko, Fizz und Ahri. Wie kann ich dir sonst helfen?",
        "talon": "Dieser Champion wird gekontert von Lee Sin, Diana, Kayle, Riven und Pantheon. Wie kann ich dir sonst helfen?",
        "taric": "Dieser Champion wird gekontert von Sivir, Lulu, Nami, Morgana und Varus. Wie kann ich dir sonst helfen?",
        "teemo": "Dieser Champion wird gekontert von Yorick, Pantheon, Akali, Rumble und Jayce. Wie kann ich dir sonst helfen?",
        "thresh": "Dieser Champion wird gekontert von Lulu, Morgana, Alistar, Lucian und Janna. Wie kann ich dir sonst helfen?",
        "tristana": "Dieser Champion wird gekontert von Corki, Draven, Lucian, Caitlyn und Sivir. Wie kann ich dir sonst helfen?",
        "trundle": "Dieser Champion wird gekontert von Sona, Jax, Kennen, Teemo und Darius. Wie kann ich dir sonst helfen?",
        "tryndamere": "Dieser Champion wird gekontert von Teemo, Jax, Renekton, Malphite und Pantheon. Wie kann ich dir sonst helfen?",
        "twisted Fate": "Dieser Champion wird gekontert von Fizz, Diana, Ahri, LeBlanc und Kassadin. Wie kann ich dir sonst helfen?",
        "twitch": "Dieser Champion wird gekontert von Caitlyn, Jinx, Lee Sin, Corki und Draven. Wie kann ich dir sonst helfen?",
        "udyr": "Dieser Champion wird gekontert von Ashe, Trundle, Jax, Kayle und Teemo. Wie kann ich dir sonst helfen?",
        "urgot": "Dieser Champion wird gekontert von Soraka, Bard, Sivir, Nami und Twitch. Wie kann ich dir sonst helfen?",
        "varus": "Dieser Champion wird gekontert von Graves, Lucian, Tristana, Sivir und Blitzcrank. Wie kann ich dir sonst helfen?",
        "vayne": "Dieser Champion wird gekontert von Caitlyn, Draven, Quinn, Ashe und Graves. Wie kann ich dir sonst helfen?",
        "veigar": "Dieser Champion wird gekontert von Fizz, Zed, Ryze, Talon und Kassadin. Wie kann ich dir sonst helfen?",
        "vel'Koz": "Dieser Champion wird gekontert von Yasuo, LeBlanc, Fizz, Katarina und Zed. Wie kann ich dir sonst helfen?",
        "vi": "Dieser Champion wird gekontert von Riven, Jax, Lee Sin, Darius und Teemo. Wie kann ich dir sonst helfen?",
        "viktor": "Dieser Champion wird gekontert von Brand, Syndra, Fizz, LeBlanc und Ziggs. Wie kann ich dir sonst helfen?",
        "vladimir": "Dieser Champion wird gekontert von Swain, Riven, Irelia, Malzahar und Xin Zhao. Wie kann ich dir sonst helfen?",
        "volibear": "Dieser Champion wird gekontert von Teemo, Renekton, Kayle, Pantheon und Elise. Wie kann ich dir sonst helfen?",
        "warwick": "Dieser Champion wird gekontert von Yorick, Udyr, Kayle, Olaf und Lee Sin. Wie kann ich dir sonst helfen?",
        "wukong": "Dieser Champion wird gekontert von Darius, Riven, Illaoi, Fiora und Mundo. Wie kann ich dir sonst helfen?",
        "xerath": "Dieser Champion wird gekontert von Ahri, Fizz, LeBlanc, Zed und Syndra. Wie kann ich dir sonst helfen?",
        "xin Zhao": "Dieser Champion wird gekontert von Jax, Malphite, Pantheon, Teemo und Volibear. Wie kann ich dir sonst helfen?",
        "yasuo": "Dieser Champion wird gekontert von Jax, Riven, Fiora, Akali und Darius. Wie kann ich dir sonst helfen?",
        "yorick": "Dieser Champion wird gekontert von Cho'Gath, Trundle, Xin Zhao, Riven und Nunu. Wie kann ich dir sonst helfen?",
        "zac": "Dieser Champion wird gekontert von Vi, Zilean, Renekton, Vladimir und Yorick. Wie kann ich dir sonst helfen?",
        "zed": "Dieser Champion wird gekontert von Kayle, Lissandra, Irelia, Jax und Singed. Wie kann ich dir sonst helfen?",
        "ziggs": "Dieser Champion wird gekontert von LeBlanc, Yasuo, Talon, Fizz und Akali. Wie kann ich dir sonst helfen?",
        "zilean": "Dieser Champion wird gekontert von Morgana, Blitzcrank, Annie, Sivir und Lux. Wie kann ich dir sonst helfen?",
        "zyra": "Dieser Champion wird gekontert von Katarina, Fizz, Diana, Akali und Kassadin. Wie kann ich dir sonst helfen?"
    }
};
